[[logging-and-debugging]]
= Logging and Debugging

== Configuring Logging

Jet, like Hazelcast IMDG, does not depend on a specific logging
framework and has built-in adapters for a variety of logging frameworks.
You can also write a new adapter to integrate with loggers Jet doesn't
natively support. To use one of the built-in adapters, set the
`hazelcast.logging.type` property to one of the following:

* `jdk`: java.util.logging (default)
* `log4j`: Apache Log4j
* `log4j2`: Apache Log4j 2
* `slf4j`: SLF4J
* `none`: Turn off logging

For example, to configure Jet to use Log4j, you can do one of the
following:

[source]
----
include::{javasource}/LogDebug.java[tag=s1]
----

or

[source]
----
include::{javasource}/LogDebug.java[tag=s2]
----

For more detailed information about how to configure logging, please
refer to the {hz-refman}#logging-configuration[IMDG reference manual].

== Inspecting Output of Individual Stages

While debugging your pipeline you'll want to see the output of an
individual stage. You can achieve it by using the
{jet-javadoc}/GeneralStage.html#peek--[`peek()`] stage. For example:

[source]
----
include::{javasource}/LogDebug.java[tag=s3]
----

<1> Captures all the word tokens entering the aggregating stage

If you run it like this:

[source]
----
include::{javasource}/LogDebug.java[tag=s4]
----

this is how your output may look:

....
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#1
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: quick
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#2
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: brown
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#0
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: the
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#4
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: dog
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#3
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: lazy
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#0
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: jumped
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#2
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: the
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#1
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: over
Mar 20, 2018 2:43:24 PM com.hazelcast.jet.impl.processor.PeekWrappedP.filter#3
INFO: [192.168.5.12]:5702 [jet] [0.6] Output to ordinal 0: fox
....

The logger name of
`com.hazelcast.jet.impl.processor.PeekWrappedP.filter#1` consists of the
following parts:

* `com.hazelcast.jet.impl.processor.PeekWrappedP`: the type of the
processor writing the log message
* `filter`: the name of the vertex the processor belongs to
* `#0`: index of the processor within the vertex. The index is unique
cluster-wide.

For more information about logging when using the Core API, see the
<<inspecting-processor-input-and-output, Best Practices>> section.
