[[job]]
= Submit a Jet Job and Manage its Lifecycle

This is how you submit a Jet pipeline for execution:

[source]
----
include::{javasource}/ManageJob.java[tag=s1]
----

If you want to submit a Core API DAG, the syntax is identical:

[source]
----
include::{javasource}/ManageJob.java[tag=s2]
----

Job submission is a fire-and-forget action: once a client submits it,
the job has a life of its own independent of the submitter. It can
disconnect and any other client or Jet member can obtain its own `Job`
instance that controls the same job.

You can use the same API to submit a job from either a client machine or
directly on an instance of a Jet cluster member. The same `Job` instance
can be submitted for execution many times.

== JobConfig

To gain more control over how Jet will run your job, you can pass in
a `JobConfig` instance. For example, you can give your job a human-
readable name:

[source]
----
include::{javasource}/ManageJob.java[tag=s3]
----

In the <<practical-considerations, Practical Considerations>> section
we'll deepen this story and explain how to use the `JobConfig` to
to submit a job to a Jet cluster in production.

== Manage a Submitted Job

`jet.newJob()` returns a {jet-javadoc}/Job.html[Job] object, which you
can use to monitor the job and change its status. You can get the job's
name, configuration, and submission time via `job.getName()`,
`job.getConfig()`, and `job.getSubmissionTime()`. `job.getStatus()`
will give you the current status of the job (running, failed, completed
etc.). You can also call `Job.getFuture()` to block until the job
completes and then get its final outcome (either success or failure).

Jet does not support canceling the job with `future.cancel()`, instead
you must call `job.cancel()`. This is due to the mismatch in the
semantics between `future.cancel()` on one side and `job.cancel()` plus
`job.getStatus()` on the other: the future immediately transitions to
"`completed by cancellation`", but it will take some time until the
actual job in the cluster changes to that state. Not to confuse the
users with these differences we decided to make `future.cancel()` fail
with an exception.

== Get a List of all Submitted Jobs

Jet keeps an inventory of all the jobs submitted to it, including those
that have already completed. Access the full list with `jet.getJobs()`.
You can use any `Job` instance from that list to monitor and manage a
job, whether it was you or some other client that submitted it.

This example tells you what Jet has been up to in the last five minutes:

[source]
----
include::{javasource}/ManageJob.java[tag=s4]
----

To get a more focused list of jobs, you can call `jet.getJobs(name)` to
get all the jobs with that name that were submitted since Jet started,
or `jet.getJob(name)` to get just the latest such job.

Here's how you can check the statistics on a job named `my-job`:

[source]
----
include::{javasource}/ManageJob.java[tag=s5]
----
