= Configuration

You can configure Hazelcast Jet either programmatically or
declaratively (XML).

== Programmatic Configuration

Programmatic configuration is the simplest way to configure Jet. You
instantiate a {jet-javadoc}/config/JetConfig.html[`JetConfig`] and set
the desired properties. For example, the following will configure Jet to
use only two threads in its _cooperative multithreading_ pool:

[source]
----
include::{javasource}/Configuration.java[tag=s1]
----

== Declarative Configuration

If you don't pass an explicit `JetConfig` object when constructing a Jet
instance, it will perform the following lookup procedure:

1. Read the system property `hazelcast.jet.config`. If it starts with
   `classpath:`, treat it as a classpath resource, otherwise it's a file
   pathname. If it's defined but Jet can't find the file it specifies,
   startup fails.
2. Look for `hazelcast-jet.xml` in the working directory.
3. Look for `hazelcast-jet.xml` in the classpath.
4. Load the default XML configuration packaged in Jet's JAR.

An example configuration looks like the following:

[source,xml]
----
<hazelcast-jet xsi:schemaLocation="http://www.hazelcast.com/schema/jet-config hazelcast-jet-config-0.5.xsd"
               xmlns="http://www.hazelcast.com/schema/jet-config"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <instance>
        <!-- number of threads in the cooperative thread pool -->
       <cooperative-thread-count>8</cooperative-thread-count>
        <!-- period between flow control packets in milliseconds -->
       <flow-control-period>100</flow-control-period>
        <!-- directory for temporary files -->
       <temp-dir>/var/tmp/jet</temp-dir>
        <!-- number of backup copies to configure for Hazelcast IMaps used internally in a Jet job -->
       <backup-count>1</backup-count>
    </instance>
    <properties>
       <property name="custom.property">custom property</property>
    </properties>
    <edge-defaults>
        <!-- capacity of the concurrent SPSC queue between each two processors -->
       <queue-size>1024</queue-size>

        <!-- maximum packet size in bytes, only applies to distributed edges -->
       <packet-size-limit>16384</packet-size-limit>

        <!-- receive window size multiplier, only applies to distributed edges -->
       <receive-window-multiplier>3</receive-window-multiplier>
    </edge-defaults>
    <!-- custom properties which can be read within a ProcessorSupplier -->
</hazelcast-jet>
----

The following are the configuration elements for Hazelcast Jet:

* Cooperative Thread Count: number of threads Jet will create in its
_cooperative multithreading_ pool. The default value is
`Runtime.getRuntime().availableProcessors()`
* Temp Directory: directory where Jet can create temporary files such
as JAR files submitted by clients. Jet will create a temp directory and
delete it on exit.
* Flow Control Period: Jet uses a flow control mechanism between
cluster members to prevent a slower vertex from getting overflowed with
data from a faster upstream vertex. Each receiver regularly reports to
each sender how much more data it may send over a given DAG edge. This
option sets the duration (in milliseconds) of the interval between
flow-control packets. Its default value is 100ms.
* Backup Count: Sets the number of synchronous backups to configure on
IMaps that Jet needs internally to store job metadata and snapshots. The
maximum allowed value is 6. The default value is 1.
* Edge Defaults: The default values to be used for all edges. See the
section on <<fine-tuning-edges, Tuning Edges>>.

== Configure the Underlying Hazelcast Instance

Each Jet member or client has its underlying Hazelcast member or client.
Please refer to the
{hz-refman}#understanding-configuration[Hazelcast Reference Manual]
for specific configuration options for Hazelcast IMDG.

=== Programmatic

You can configure the underlying Hazelcast IMDG member as follows:

[source]
----
include::{javasource}/Configuration.java[tag=s2]
----

Similarly, you can also configure the underlying Hazelcast client:

[source]
----
include::{javasource}/Configuration.java[tag=s3]
----

=== Declarative

Hazelcast IMDG can also be configured declaratively. Please refer to the
{hz-refman}#configuring-declaratively[Hazelcast Reference Manual]
for information on how to do this.

== Spring Integration

You can configure and start a Hazelcast Jet instance as a component in
the Spring Application Context. You can use the plain `bean` element
and define individual properties on a `JetConfig` instance, but Jet
provides its own schema-based configuration which will make this much
less verbose.

=== Approach 1: Use the Plain `bean` Element

You can declare Hazelcast Jet objects using the default Spring beans
namespace. Here is an example for a Hazelcast Jet Instance declaration:

[source, xml]
----
<bean id="instance" class="com.hazelcast.jet.Jet" factory-method="newJetInstance">
    <constructor-arg>
        <bean class="com.hazelcast.jet.config.JetConfig">
            <property name="hazelcastConfig">
                <bean class="com.hazelcast.config.Config">
                    <!-- ... -->
                </bean>
            </property>
            <property name="instanceConfig">
                <bean class="com.hazelcast.jet.config.InstanceConfig">
                    <property name="cooperativeThreadCount" value="2"/>
                </bean>
            </property>
            <property name="defaultEdgeConfig">
                <bean class="com.hazelcast.jet.config.EdgeConfig">
                    <property name="queueSize" value="2048"/>
                </bean>
            </property>
            <property name="properties">
                <props>
                    <prop key="foo">bar</prop>
                </props>
            </property>
        </bean>
    </constructor-arg>
</bean>

<bean id="map" factory-bean="instance" factory-method="getMap">
    <constructor-arg value="my-map"/>
</bean>
----

=== Approach 2: Use `jet:instance`

Hazelcast Jet provides its own Spring config schema. Add the namespace
declaration `xmlns:jet=“http://www.hazelcast.com/schema/jet-spring”`
to the `beans` element and then use the *_jet_* namespace prefix.
Make sure you added `hazelcast-jet-spring.jar` to the classpath.

Here's how your namespace and schema instance declarations may look:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:jet="http://www.hazelcast.com/schema/jet-spring"
       xmlns:hz="http://www.hazelcast.com/schema/spring"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
        http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.10.xsd
        http://www.hazelcast.com/schema/jet-spring
        http://www.hazelcast.com/schema/jet-spring/hazelcast-jet-spring-0.6.xsd">
        <!-- ... -->
 </beans>
----

==== Configuring the Hazelcast Jet Instance

[source,xml]
----
<jet:instance id="instance">
    <hz:config>
        <hz:spring-aware/>
        <hz:group name="jet"/>
        <hz:network port="5701" port-auto-increment="false">
            <hz:join>
                <hz:multicast enabled="false"/>
                <hz:tcp-ip enabled="true">
                    <hz:member>127.0.0.1:5701</hz:member>
                </hz:tcp-ip>
            </hz:join>
        </hz:network>
        <hz:map name="map" backup-count="3">
        </hz:map>
    </hz:config>
    <jet:instance-config cooperative-thread-Count="2"/>
    <jet:default-edge-config queue-size="2048"/>
    <jet:properties>
        <hz:property name="foo">bar</hz:property>
    </jet:properties>
</jet:instance>
----

==== Configure a Jet Client

[source,xml]
----
<jet:client id="jet-client">
    <jet:group name="jet"/>
    <jet:network>
        <hz:member>127.0.0.1:5701</hz:member>
    </jet:network>
    <jet:spring-aware/>
</jet:client>
----

==== Additional Bean Types Supported by the Jet Namespace

You can obtain the underlying `HazelcastInstance` from the Jet instance
as a bean and use it to obtain these Hazelcast IMDG beans:

 - map
 - list
 - multiMap
 - replicatedmap
 - queue
 - topic
 - set
 - executorService
 - idGenerator
 - atomicLong
 - atomicReference
 - semaphore
 - countDownLatch
 - lock

Here are short examples for each of them:

[source,xml]
----
<jet:hazelcast jet-instance-ref="jet-instance" id="hazelcast-instance"/>

<jet:map instance-ref="jet-instance" name="my-map" id="my-map-bean"/>

<jet:list instance-ref="jet-client" name="my-list" id="my-list-bean"/>

<hz:multiMap id="multiMap" instance-ref="hazelcast-instance" name="my-multiMap"/>

<hz:replicatedMap id="replicatedMap" instance-ref="hazelcast-instance" name="my-replicatedMap"/>

<hz:queue id="queue" instance-ref="hazelcast-instance" name="my-queue"/>

<hz:topic id="topic" instance-ref="hazelcast-instance" name="my-topic"/>

<hz:set id="set" instance-ref="hazelcast-instance" name="my-set"/>

<hz:executorService id="executorService" instance-ref="hazelcast-instance" name="my-executorService"/>

<hz:idGenerator id="idGenerator" instance-ref="hazelcast-instance" name="my-idGenerator"/>

<hz:atomicLong id="atomicLong" instance-ref="hazelcast-instance" name="my-atomicLong"/>

<hz:atomicReference id="atomicReference" instance-ref="hazelcast-instance" name="my-atomicReference"/>

<hz:semaphore id="semaphore" instance-ref="hazelcast-instance" name="my-semaphore"/>

<hz:countDownLatch id="countDownLatch" instance-ref="hazelcast-instance" name="my-countDownLatch"/>

<hz:lock id="lock" instance-ref="hazelcast-instance" name="my-lock"/>
----

Hazelcast Jet also supports _lazy-init_, _scope_ and _depends-on_ bean
attributes.

[source,xml]
----
<jet:instance id="instance" lazy-init="true" scope="singleton">
<!-- ... -->
</jet:instance>
<jet:client id="client" scope="prototype" depends-on="instance">
<!-- ... -->
</jet:client>
----

=== Annotation-Based Configuration

Annotation-Based Configuration does not require any XML definition.
Simply create a configuration class annotated with `@Configuration` and
provide a `JetInstance` as a bean by annotating the method with `@Bean`.

[source,java]
----
@Configuration
public class AppConfig {

    @Bean
    public JetInstance instance() {
        return Jet.newJetInstance();
    }
}
----

=== Enabling SpringAware Objects

Hazelcast IMDG has a special annotation, `@SpringAware`, which
enables you to initialize the object with spring context.

When a job is submitted to the cluster, processors are created
by Hazelcast Jet on each member. By marking your processor with
`@SpringAware`, you make spring context accessible to your
processor which gives you the ability:

 - to apply bean properties
 - to apply factory callbacks such as `ApplicationContextAware`,
   `BeanNameAware`
 - to apply bean post-processing annotations such as
   `InitializingBean`, `@PostConstruct`

You need to configure Hazelcast Jet with `<hz:spring-aware/>`
tag or set `SpringManagedContext` programmatically to enable
spring-aware objects. Code samples for
https://github.com/hazelcast/hazelcast-jet-code-samples/blob/master/spring/src/main/java/jet/spring/XmlConfigurationWithSchemaSample.java[declarative]
and
https://github.com/hazelcast/hazelcast-jet-code-samples/blob/master/spring/src/main/java/jet/spring/AnnotationBasedConfigurationSample.java[annotation-based]
configurations are available at our Code Samples repo.
