
[[get-started]]
= Get Started

In this section we'll get you started using Hazelcast Jet. We'll
show you how to set up a Java project with the proper dependencies and a
quick Hello World example to verify your setup.

[[requirements]]
== Requirements

In the good tradition of Hazelcast products, Jet is distributed as a JAR
with no other dependencies. It requires JRE version 8 or higher to run.

[[maven-gradle]]
== Using Maven and Gradle

The easiest way to start using Hazelcast Jet is to add it as a
dependency to your project.

Hazelcast Jet is published on the Maven repositories. Add the following
lines to your `pom.xml`:

[source,xml,subs="attributes+"]
----
<dependencies>
  <dependency>
    <groupId>com.hazelcast.jet</groupId>
    <artifactId>hazelcast-jet</artifactId>
    <version>{jet-version}</version>
  </dependency>
</dependencies>
----

If you prefer to use Gradle, execute the following command:

[source,groovy,subs="attributes+"]
----
compile 'com.hazelcast.jet:hazelcast-jet:{jet-version}'
----


[[downloading]]
== Downloading

Alternatively you can download the latest http://jet.hazelcast.org/download[distribution package of
Hazelcast Jet]
and add the `hazelcast-jet-<version>.jar` file to your classpath.

[[distribution-package]]
=== Distribution Package

The distribution package contains the following scripts to help you get
started with Hazelcast Jet:

* `bin/jet-start.sh` and `bin/jet-start.bat` start a new Jet member in
the current directory.
* `bin/jet-stop.sh` and `bin/jet-stop.bat` stop the member started in
the current directory.
* `bin/jet-submit.sh` and `bin/jet-submit.bat` submit a Jet computation
job that was packaged in a self-contained JAR file.
* `bin/cluster.sh` provides basic functionality for Hazelcast cluster
manager, such as changing the cluster state, shutting down the cluster
or forcing the cluster to clean its persisted data.

[[verify-your-setup]]
== Verify Your Setup

You can verify your setup by running this simple program. It processes
the contents of a Hazelcast `IList` that contains lines of text, finds
the number of occurrences of each word in it, and stores its results
in a Hazelcast `IMap`. In a distributed  computation job the input and
output cannot be simple in-memory structures like a Java `List`; they
must reside in the cluster so any member can access them. This is why we
use Hazelcast structures.

[source]
----
include::{javasource}/HelloWorld.java[]
----

You should expect to see a lot of logging output from Jet (sent to
`stderr`) and two lines on `stdout`:

----
Count of hello: 4
Count of world: 5
----
