
[[get-started]]
= Get Started

In this section we'll get you started using Hazelcast Jet. We'll show
you how to set up a Java project with the proper dependencies and a
quick Hello World example to verify your setup.

[[requirements]]
== Requirements

In the good tradition of Hazelcast products, Jet is distributed as a JAR
with no other dependencies. It requires JRE version 8 or higher to run.

== Install Hazelcast Jet

The easiest way to start using Hazelcast Jet is to add it as a
dependency to your project.

Hazelcast Jet is published on the Maven repositories. Add the following
lines to your `pom.xml`:

[source,xml,subs="attributes+"]
----
<dependencies>
  <dependency>
    <groupId>com.hazelcast.jet</groupId>
    <artifactId>hazelcast-jet</artifactId>
    <version>{jet-version}</version>
  </dependency>
</dependencies>
----

If you prefer to use Gradle, execute the following command:

[source,groovy,subs="attributes+"]
----
compile 'com.hazelcast.jet:hazelcast-jet:{jet-version}'
----

Alternatively you can download the latest
http://jet.hazelcast.org/download[distribution package of Hazelcast Jet]
and add the `hazelcast-jet-{jet-version}.jar` file to your classpath.

== Install Hazelcast Jet Enterprise (Optional)

Hazelcast Jet Enterprise is a commercial edition of Hazelcast Jet. It's
built on top of Hazelcast Jet open source and extends it with the
following features:

* <<configuring-tls-enterprise-only, Security Suite>>
* Lossless Recovery (in Jet 1.0)
* Rolling Job Upgrades (in Jet 1.0)
* Enterprise PaaS Deployment Environment
(https://docs.pivotal.io/partners/hazelcast-jet/index.html[Pivotal Cloud
Foundry], Openshift Container Platform (Jet 1.0))

Hazelcast Jet Enterprise is available on a Hazelcast Maven repository.
Add the following lines to your `pom.xml`:

[source,xml,subs="attributes+"]
----
<repository>
   <id>Hazelcast Private Snapshot Repository</id>
   <url>https://repository-hazelcast-l337.forge.cloudbees.com/snapshot/</url>
</repository>
<repository>
   <id>Hazelcast Private Release Repository</id>
   <url>https://repository-hazelcast-l337.forge.cloudbees.com/release/</url>
</repository>
----

[source,xml,subs="attributes+"]
----
<dependency>
   <groupId>com.hazelcast</groupId>
   <artifactId>hazelcast-enterprise</artifactId>
   <version>{jet-version}</version>
</dependency>
----

You can download the Hazelcast Jet Enterprise package from
https://hazelcast.com/hazelcast-enterprise-download/[hazelcast.com].

=== Set the License Key

To use Hazelcast Jet Enterprise, you must set the license key using one
of the configuration methods shown below. You can request a trial
license key at https://hazelcast.com/hazelcast-enterprise-download/[hazelcast.com].

Hazelcast Jet Enterprise license keys are required only to run the Jet
cluster. A Jet client can access the Enterprise features without the
license key.

The license key can be configured using one of the following methods:

==== Hazelcast Configuration File

Replace the value for the `<license-key>` tag inside the `hazelcast.xml`
file in the config folder:

[source,xml,subs="attributes+"]
----
  <hazelcast ..>
      ...
      <license-key>ENTER LICENSE KEY HERE</license-key>
      ...
  </hazelcast>
----

===== Programmatic Configuration

License key also can be set in the Jet config object as follows:

[source,java]
----
JetConfig config = new JetConfig();
config.getHazelcastConfig().setLicenseKey( "Your Enterprise License Key" );
----

==== System Property

Set the following system property:

----
-Dhazelcast.enterprise.license.key=Your Enterprise License Key
----

=== Hazelcast Jet Management Center

Hazelcast Jet Management Center is a management and monitoring suite
providing a live overview of the Hazelcast Jet cluster. It's a
standalone tool with a web console.

Please see the
https://docs.hazelcast.org/docs/jet-management-center/latest/manual/[Hazelcast
Jet Management Center Reference Manual] for the installation
instructions.

[[verify-your-setup]]
== Verify Your Setup With a Word Count Example

You can verify your setup by running this simple program. It processes
the contents of a Hazelcast `IList` that contains lines of text, finds
the number of occurrences of each word in it, and stores its results
in a Hazelcast `IMap`. In a distributed  computation job the input and
output cannot be simple in-memory structures like a Java `List`; they
must be accessible to any member of the computing cluster and must
persist after a job ends. This is why we use Hazelcast structures.

[source]
----
include::{javasource}/HelloWorld.java[]
----

You should expect to see a lot of logging output from Jet (sent to
`stderr`) and two lines on `stdout`:

----
Count of hello: 4
Count of world: 5
----

[[java-util-stream]]
== Reuse Your java.util.stream Knowledge

If you've already used Java's Stream API, you'll find many similarities
in Jet's Pipeline API. They both construct a processing pipeline by
adding processing steps (stages). Both are FP-oriented APIs with lambdas
playing a key role. Simple transformations like map/filter even look
exactly the same. The main concern is knowing where the similiarities
end. Here are some typical gotchas if the Stream API has set some
expectations for you:

- All lambdas in Jet <<serializable-lambda, get serialized>> so they can
be sent to remote cluster members. If your lambda captures a variable
from the surrounding scope, that variable's contents must be serialized
as well. If you refer to an instance variable, the entire instance
holding it must be serialized. It's quite easy to accidentally capture
and serialize the entire `this` object and everything it refers to.

- The pipeline you construct doesn't execute itself, you must explicitly
{jet-javadoc}/JetInstance.html#newJob-com.hazelcast.jet.pipeline.Pipeline-[submit]
it to a Jet cluster.

- Since you're submitting the computation to an external system, you
don't get the result in the return value of a method call. The pipeline
explicitly specifies where it will store the results (to a
<<pipeline-source-sink, data sink>>).

- Whereas in the Stream API aggregation is the terminal step, the one
that immediately makes your pipeline execute, in Jet it is just another
transformation (an intermediate step).

Finally, you'll notice that Jet's Pipeline API is much more powerful
than the Stream API. Here are a few highlights:

- <<cogroup, joining streams>>
- <<windowed-aggregation, windowed aggregation over infinite streams>>
- <<fault-tolerance, fault tolerance>>
- <<source-sink-connectors, connectors to 3rd party systems>>

=== Example: List Transformation

Here's a simple example of list transformation with the Stream API:

[source]
----
include::{javasource}/GetStarted.java[tag=s1a]
----

Here's the equivalent in Jet. Note that we're transforming Hazelcast
`IList` s:

[source]
----
include::{javasource}/GetStarted.java[tag=s1b]
----

=== Example: Grouping and Aggregation

Here's an example of grouping and aggregation with the Stream API. We
compute a histogram of words by their length:

[source]
----
include::{javasource}/GetStarted.java[tag=s2a]
----

And here's how to aggregate in Jet:

[source]
----
include::{javasource}/GetStarted.java[tag=s2b]
----

Note that the result of `aggregate` is just another pipeline stage, you
can apply more transforms to it before draining to the sink.

=== Example: Collector vs. AggregateOperation

If you have ever written your own
{jdk-javadoc}/java/util/stream/Collector.html[Collector] for the
Stream API, you'll find that Jet's <<implement-your-aggregate-operation,
AggregateOperation>> is quite similar and you can transfer your skill
to it.

Here's a Stream API collector that computes the sum of input items:

[source]
----
include::{javasource}/GetStarted.java[tag=s3a]
----

And here's Jet's aggregate operation doing the same:

[source]
----
include::{javasource}/GetStarted.java[tag=s3b]
----

Compared to `Collector`, `AggregateOperation` defines two more
primitives:

- `deduct` reverses a previous `combine`. It's an optional primitive and
serves to optimize sliding window aggregation.
- `export` is similar to `finish` and here we actually define both using
the same lambda. The difference is that `export` must preserve the
accumulator's state and `finish` doesn't. There are opportunities for
optimizations in `finish` that would be incompatible with our rolling
aggregation (which must use `export`).
