= File and Socket

Hazelcast Jet provides file and TCP/IP socket connectors that have
limited production use, but are simple and can be very useful in an
early rapid prototyping phase. They assume the data is in the form of
plain text and emit/receive data items which represent individual lines
of text.

These connectors are not fault-tolerant. On job restart they behave the
same as on initial start. The sources don't do snapshotting. The sinks
don't suppress duplicate data.

== File Sources

The file sources are designed to work with the local file system. They
expect to see on each member just the files that member should read. You
can achieve the effect of a distributed source if you manually prepare a
different set of files on each member.

There are two flavors of the file source: bounded and unbounded.

Here's an example with the
{jet-javadoc}/pipeline/Sources.html#files-java.lang.String-java.nio.charset.Charset-java.lang.String-com.hazelcast.jet.function.DistributedBiFunction-[bounded source]:

[source]
----
include::{javasource}/FileAndSocket.java[tag=s1]
----

This will log on each Jet member the contents of all the files in the
specified directory. When the source reads all the files, the job
completes. If the files change while the job is running, the behavior
is undefined.

Here's an example with the
{jet-javadoc}/pipeline/Sources.html#fileWatcher-java.lang.String-java.nio.charset.Charset-java.lang.String-[unbounded source]:

[source]
----
include::{javasource}/FileAndSocket.java[tag=s2]
----

It will start by logging on each member the contents of all the files in
the directory and then will switch to watching the directory for
changes. It will read both new files and the content added to the
existing files. Files must be updated in an append-only fashion; if the
existing content changes, the behavior is undefined.

If you delete the watched directory, the job will complete.

=== File Sink

The
{jet-javadoc}/pipeline/Sinks.html#files-java.lang.String-com.hazelcast.jet.function.DistributedFunction-java.nio.charset.Charset-boolean-[file sink]
can work with either a local or a shared network file system. Each
member will write to different filenames. You can achieve the effect of
a distributed sink if you manually collect all the output files on all
members and combine their contents.

Here's a small example of usage:

[source]
----
include::{javasource}/FileAndSocket.java[tag=s3]
----

== Socket Source

These connectors open a blocking client TCP/IP socket and
send/receive data over it. As already noted, the data must be in the
form of lines of plain text.

The socket source can be used to receive text input over a network socket.

Each underlying processor of the Socket Source connector opens its
own client socket and asks for data from it. The user supplies the
`host:port` connection details. The server side should ensure a
meaningful dispersion of data among all the connected clients, but
how it does it is outside of Jet's control.

You can study a comprehensive
{jet-samples}/streaming/socket-connector/src/main/java/StreamTextSocket.java[code sample]
including a sample socket server using Netty.

=== Sink

The Socket Sink also opens one client socket per processor and
pushes lines of text into it. It is the duty of the server-side
system to collect the data from all the concurrently connected
clients.
